home/urls.py
from django.urls import path
from .views import *

app_name='home'
urlpatterns = [
    path('', index, name='index'),
    path('confirmation/', confirmation, name='confirmation'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=50,primary_key=True)
    status = models.CharField(max_length=50)
    timestamp = models.DateTimeField(auto_now_add = True, null = True)

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from .models import User

class User_Input(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : "What's your name?",
        'type' : 'text',
        'maxlength' : '50',
        'required' : True,
        'label' : '',
    }))
    status = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : "Tell us how are you feeling today",
        'type' : 'text',
        'maxlength' : '50',
        'required' : True,
        'label' : '',
    }))

home/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import User

# Create your views here.
def index(request):
    if request.method == "POST":
        form = User_Input(request.POST)
        if (form.is_valid()):
            new_name = form.cleaned_data['name']
            new_status = form.cleaned_data['status']
            response = {'name':new_name, 'status':new_status}
            return render(request, 'confirmation.html', response)
    else:
        form = User_Input()
    user = User.objects.all()
    response = {'user': user}
    return render(request, 'index.html', response)


def confirmation(request):
    if request.method == "POST":
        form = User_Input(request.POST)
        if (form.is_valid()):
            new_user = User()
            new_user.name = form.cleaned_data['name']
            new_user.status = form.cleaned_data['status']
            new_user.save()
            return redirect('home:index')
    else:
        form = User_Input()
    return render(request, 'confirmation.html')

home/templates/confirmation.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style>
        html, body {
          width: 100%;
          height: 100%;
          margin: 0;
          padding: 0;
          overflow-x: hidden;
        }
    </style>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Poppins:wght@400;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
    <title>Welcome, User!</title>
  </head>
<body>
    <div class="row five">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h1 class="info">Submit?</h1>
            <form action="{% url 'home:confirmation' %}" method="POST">
                {% csrf_token %}
                <div class="row six">
                    <input type="text" class="form-control" id="name" name="name" maxlength="50" readonly value="{{ name }}">
                    <input type="text" class="form-control" id="status" name="status" maxlength="50" readonly value="{{ status }}">
                </div>
                <div class="row seven">
                    <input type="submit" name="confirmation" value="Confirm" id="confirmation">
                    <a href="{% url 'home:index' %}" id="cancel">Cancel</a>        
                </div>
            </form> 

        </div>
        <div class="col-md-3"></div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>        
</body>
</html>

home/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style>
        html, body {
          width: 100%;
          height: 100%;
          margin: 0;
          padding: 0;
          overflow-x: hidden;
        }
    </style>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Poppins:wght@400;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
    <title>Welcome, User!</title>
  </head>
  <body>
    <div class="row one">
        <div class="col-md-3">
            <div class="row alternate">
                <p id="name">Ferdi Sungkar</p>
            </div>
        </div>
        <div class="col-md-6">
            <h1 id="welcome">Hello!</h1>
        </div>
        <div class="col-md-3"></div>
    </div>
    <div class="row two">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" id="name" name="name" maxlength="50" placeholder="What's your name?" required>
                    <br>
                    <input type="text" class="form-control" id="status" name="status" maxlength="50" placeholder="Tell us how are you feeling today" required>
                    <div class="row three">
                            <button type="submit" class="btn">Submit</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-3"></div>
        <div class="row four">
            <div class="col-md-3"></div>
            <div class="col-md-9 res">
              <h1 id="responses">Responses</h1>
              <div class="response">
                {% for i in user %}
                <div id="res">
                  <h1 id="time">{{ i.timestamp }}</h1>
                  <h1 id="name">Name: {{ i.name }}</h1>
                  <h1 id="status">Status: {{ i.status }}</h1>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
      
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>